# Generated by Django 4.2.3 on 2023-10-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commers", "0002_remove_category_main_category_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Waiting for approval"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Pai"),
                        ],
                        default=0,
                    ),
                ),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("delivery_at", models.DateTimeField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "currency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        choices=[
                            ("Customer", "Customer"),
                            ("Product Manager", "Product Manager"),
                            ("Sales Specialist", "Sales Specialist"),
                            ("Sales Manager", "Sales Manager"),
                            ("Admin", "Admin"),
                        ],
                        default="Customer",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "cartId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Sepet ID"
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Shopping Cart",
                "verbose_name_plural": "Shopping Carts",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=80, unique=True)),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Telefon Numarası"),
                ),
                ("address", models.TextField(max_length=150, verbose_name="Adres")),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("tax_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "pending"), (1, "activated"), (2, "anonymous")]
                    ),
                ),
                ("built_in", models.BooleanField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.role"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cart_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="users.shoppingcart",
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commers.model",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping Cart Item",
                "verbose_name_plural": "Shopping Cart Items",
            },
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="OfferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("buying_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit_margin", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "offer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.offer"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Item",
                "verbose_name_plural": "Offer Items",
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log", models.CharField(max_length=50)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.offer"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
            },
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
            },
        ),
    ]
