# Generated by Django 4.2.4 on 2023-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.CreateModel(
            name="PhoneBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200)),
                ("soyad", models.CharField(max_length=200)),
                ("tel", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=250)),
                (
                    "image",
                    models.ImageField(
                        upload_to="phone_books", verbose_name="Kapak Fotografı"
                    ),
                ),
                ("adres", models.TextField(max_length=500)),
                ("slug", models.SlugField(editable=False, max_length=270, unique=True)),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="phone_books", to="phone_books.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kişi",
                "verbose_name_plural": "Kişiler",
            },
        ),
    ]
