# Generated by Django 4.2.4 on 2023-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="adres",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="email",
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
