# Generated by Django 4.2.4 on 2023-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_books", "0002_alter_phonebook_adres_alter_phonebook_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="tel",
            field=models.CharField(max_length=11),
        ),
    ]
