# Generated by Django 4.2.3 on 2023-10-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                (
                    "profit_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "is_active",
                    models.IntegerField(
                        choices=[(0, "Not Published"), (1, "Published")], default=0
                    ),
                ),
                ("builtIn", models.BooleanField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("built_in", models.BooleanField(default=True)),
                ("seq", models.IntegerField(default=0)),
                ("slug", models.SlugField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("symbol", models.CharField(max_length=3)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("update_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("sku", models.CharField(max_length=50)),
                ("stock_amount", models.IntegerField()),
                ("in_box_quantity", models.IntegerField(default=1)),
                ("seq", models.IntegerField(default=0)),
                ("buying_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("built_in", models.BooleanField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "currency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.currency",
                    ),
                ),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.imagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model",
                "verbose_name_plural": "Models",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("short_desc", models.CharField(blank=True, max_length=300, null=True)),
                ("long_desc", models.CharField(blank=True, max_length=250, null=True)),
                ("slug", models.SlugField()),
                ("seq", models.IntegerField(default=0)),
                ("is_new", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("built_in", models.BooleanField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="commers.brand"
                    ),
                ),
                ("category_id", models.ManyToManyField(to="commers.category")),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.imagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductPropertyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("seq", models.IntegerField()),
                ("built_in", models.BooleanField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Property Key",
                "verbose_name_plural": "Product Property Keys",
            },
        ),
        migrations.CreateModel(
            name="ModelPropertyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="commers.model"
                    ),
                ),
                (
                    "product_property_key_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commers.productpropertykey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Property Value",
                "verbose_name_plural": "Model Property Values",
            },
        ),
        migrations.AddField(
            model_name="model",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="commers.product"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="image_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="commers.imagemodel"
            ),
        ),
    ]
