# Generated by Django 4.2.3 on 2023-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="main_category_id",
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="model",
            name="sku",
            field=models.CharField(max_length=100),
        ),
    ]
