# Generated by Django 4.2.3 on 2023-10-23 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commers", "0002_remove_category_main_category_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductPropertyKey",
            new_name="ModelPropertyKey",
        ),
    ]
